spring:
  application:
    name: ms-auth-identityservice
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-auth:3306/world_dance_auth}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:worlddance-consul}
      port: 8500
      discovery:
        service-name: ms-auth-identityservice
        instance-id: ${spring.application.name}:${random.value}
        port: 9091
        prefer-ip-address: true
        health-check-path: /api/v1/actuator/health
        health-check-interval: 10s
        health-check-critical-timeout: 1m
        tags:
          - contextPath=/api/v1
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  main:
    allow-bean-definition-overriding: true

server:
  port: 9091
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    mongodb:
      enabled: false

jwt:
  secret: ${JWT_SECRET:F0bVQgRnuk6DRxooVWKaG0ndlgqEeI/4YXObXeOaR2Q=}

security:
  jwt:
    secret-key: ${JWT_SECRET:F0bVQgRnuk6DRxooVWKaG0ndlgqEeI/4YXObXeOaR2Q=}
    token-expiration: 3600000