spring:
  application:
    name: ms-auth-identityservice
  datasource:
    url: jdbc:mysql://localhost:3306/world_dance_auth
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    consul:
      host: ${URL_CONSUL:localhost}
      port: ${PORT_CONSUL:8500}
    discovery:
        health-check-path: /api/v1/actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${random.value}
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect # Dialecto para MySQL (traduce las consultas sql a MySQL)
    hibernate: # sub configuracion para usar el orm
      ddl-auto: none
    show-sql: true # Muestra sentencias sql traducidas a lenguaje sql
    properties: # propiedades extras de hibernate
      hibernate:
        format-sql: true # Formatear SQL en los logs para mayor legibilidad
  main:
    allow-bean-definition-overriding: true

server:
  port: 9090
  servlet:
    context-path: /api/v1

security:
  jwt:
    secret-key: ${JWT_SECRET:F0bVQgRnuk6DRxooVWKaG0ndlgqEeI/4YXObXeOaR2Q=}
